[config]
schemaVersion = "0.0.1"

[package]
namespace = "Faustvii"
name = "QoLChests"
versionNumber = "1.1.7"
description = "Quality of life changes to chests, terminals, scrapper, duplicator, turrets and drones. - Hide when empty and highlighting."
websiteUrl = "https://github.com/Faustvii/R2Mods"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.1902"
RiskofThunder-HookGenPatcher = "1.2.3"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../zip"

[[build.copy]]
source = "../bin/Release/netstandard2.0/QoLChests.dll"
target = "QoLChests.dll"

[[build.copy]]
source = "../bin/Release/netstandard2.0/publish/BetterUnityPlugin.dll"
target = "BetterUnityPlugin.dll"

[publish]
repository = "https://thunderstore.io"
communities = ["riskofrain2"]
categories = ["mods", "tweaks", "client-side"]