[config]
schemaVersion = "0.0.1"

[package]
namespace = "Faustvii"
name = "QoLChests"
versionNumber = "1.2.1"
description = "Quality of life changes to chests, terminals, scrapper, duplicator, turrets and drones. - Hide when empty and highlighting."
websiteUrl = "https://github.com/Faustvii/R2Mods"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.2117"
RiskofThunder-HookGenPatcher = "1.2.5"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../zip"

[[build.copy]]
source = "../bin/Release/netstandard2.1/QoLChests.dll"
target = "QoLChests.dll"

[publish]
repository = "https://thunderstore.io"
communities = ["riskofrain2"]
categories = ["mods", "tweaks", "client-side", "seekers-of-the-storm"]